package be.howest.sooa.o7.gui;

import be.howest.sooa.o7.domain.Trainer;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.io.File;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Hayk
 */
public class SelectTrainerDialog extends javax.swing.JDialog {

    private final MainFrame frame;
    private final static String TRAINERS_PATH = "trainers";

    public SelectTrainerDialog(MainFrame frame) {
        super(frame, true);
        this.frame = frame;
        initComponents();
        test();
        addListeners();
    }

    private void addListeners() {
        addExitButtonActionListener();
        addEditButtonActionListener();
        addAddButtonActionListener();
        addSelectButtonActionListener();
    }

    private void addExitButtonActionListener() {
        exitButton.addActionListener((ActionEvent e) -> {
            frame.close();
        });
    }

    private void addEditButtonActionListener() {

    }

    private void addAddButtonActionListener() {
        addButton.addActionListener((ActionEvent e) -> {
            showAddTrainerDialog();
        });
    }

    private void addSelectButtonActionListener() {
        selectButton.addActionListener((ActionEvent e) -> {
            if (trainersList.getModel().getSize() == 0) {
                showAddTrainerDialog();
            } else {
                String name = (String) trainersList.getSelectedItem();
                if (name == null) {
                    showWarning("Select a trainer first, please!");
                } else {
                    Trainer trainer = new Trainer(name);
                    frame.setTrainer(trainer);
                    setVisible(false);
                }
            }
        });
    }

    private boolean showAddTrainerDialog() {
        boolean success = false;
        Object[] options = {"Save Trainer", "Cancel"};
        JPanel panel = new JPanel();
        JLabel label = new JLabel("Name");
        JTextField name = new JTextField();
        panel.setLayout(new BorderLayout());
        panel.add(label, BorderLayout.NORTH);
        panel.add(name, BorderLayout.CENTER);
        Object message = "Name";
        int result = JOptionPane.showOptionDialog(this, panel,
                "New Trainer", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, "N232");
        String trainerName = name.getText().trim();
        if (result == 0) {
            if (!"".equals(trainerName)) {
                File trainerDirectory = new File(TRAINERS_PATH + "/" + trainerName);
                if (!trainerDirectory.exists()) {
                    success = trainerDirectory.mkdir();
                    test();
                    trainersList.setSelectedItem(trainerName);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Invalid trainer name. Try again, please", "Warning", JOptionPane.WARNING_MESSAGE, null);
            showAddTrainerDialog();
            }
        }
        return success;
    }

    private boolean test() {
        boolean success = false;
        String path = "trainers";
        File trainersDirectory = new File(path);
        if (trainersDirectory.exists()) {
            String[] trainers = trainersDirectory
                    .list((File current, String name1)
                            -> new File(current, name1).isDirectory());
            if (trainers.length == 0) {
                // ask to fill in name
            } else {
                DefaultComboBoxModel model = new DefaultComboBoxModel();
                for (String trainer : trainers) {
                    model.addElement(trainer);
                }
                trainersList.setModel(model);
            }
        } else {
            success = trainersDirectory.mkdir();
            // ask to fill in name
        }
        return success;
    }

    private void showWarning(String message) {
        JOptionPane.showMessageDialog(this, message, "Warning",
                JOptionPane.WARNING_MESSAGE);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        trainersList = new javax.swing.JComboBox<>();
        trainersLabel = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        selectButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Select Trainer");

        trainersLabel.setText("Trainer");

        editButton.setText("Edit...");

        addButton.setText("Add...");

        exitButton.setText("Exit");

        selectButton.setText("Select Trainer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(trainersLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(trainersList, 0, 244, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(selectButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(trainersLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trainersList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editButton)
                    .addComponent(addButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitButton)
                    .addComponent(selectButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton editButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton selectButton;
    private javax.swing.JLabel trainersLabel;
    private javax.swing.JComboBox<String> trainersList;
    // End of variables declaration//GEN-END:variables
}
